version: "3"
services:
  site:
    command: ./serve.sh
    image: docker.io/ruby:2.6.8
    working_dir: /code
    stdin_open: true
    tty: true
    volumes:
      - ".:/code:z"
      - "./vendor/bundle:/usr/local/bundle:z"
    ports:
      - 127.0.0.1:4000:4000