version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - ".:/srv/jekyll:z"
      - "./vendor/bundle:/usr/local/bundle:z"
    ports:
      - 127.0.0.1:4000:4000
