name: Build and deploy GEMOC website
on:
  push:
    branches:
      - gh-pages-edit
jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.4
          bundler-cache: true

      - name: Run the main build script
        run: bash ./build.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.

